import{S as v,a as P,i}from"./assets/vendor-DhpBV7YY.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");let l=new v(".gallery a");function h(o){const r=o.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <ul class="image-info">
        <li>👍 ${t.likes}</li>
        <li>👁️ ${t.views}</li>
        <li>💬 ${t.comments}</li>
        <li>⬇️ ${t.downloads}</li>
      </ul>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),l.refresh()}function S(){f.innerHTML=""}function g(){m.classList.add("visible")}function p(){m.classList.remove("visible")}function L(){y.classList.remove("hidden")}function q(){y.classList.add("hidden")}function B(){l&&l.refresh()}function $(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const E="https://pixabay.com/api/",M="51328495-a86ced526e026cbb82b9515b0",x=15;async function b(o,r=1){const t={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:x};return(await P.get(E,{params:t})).data}let u="",a=1;const w=15;let d=0;const O=document.querySelector(".form"),A=document.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more");O.addEventListener("submit",async o=>{o.preventDefault();const r=A.value.trim();if(!r){i.warning({message:"Please enter a search query."});return}u=r,a=1,S(),g();try{const t=await b(u,a),{hits:s,totalHits:e}=t;if(d=e,s.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(s),d>a*w&&L()}catch{i.error({message:"Something went wrong. Please try again later."})}finally{p()}});H.addEventListener("click",async()=>{a+=1,g(),q();try{const o=await b(u,a),{hits:r}=o;h(r),B(),$(),a*w>=d?i.info({message:"We're sorry, but you've reached the end of search results."}):L()}catch{i.error({message:"Failed to load more images."})}finally{p()}});
//# sourceMappingURL=index.js.map
